env: "local"
db:
   url: "postgres://postgres:123456@localhost:5432/taskmanager_db?sslmode=disable"
redis:
  address: "localhost:6379"
  password: ""
  database: 0

server:
  address: "localhost:8080"
  timeout: 4s
  iddle_timeout: 60s